BoookStore/Controllers/LivroController.cs
using BookStore.Context;
using BookStore.Domain;
using BoookStore.ViewModels;
using System;
using System.Linq;
using System.Web.Mvc;

namespace BoookStore.Controllers
{
    [RoutePrefix("livros")]
    public class LivroController : Controller // não testei eles //commit
    {
        BookStoreDataContext _db = new BookStoreDataContext(); // sem DI

        [Route("listar")]
        public ActionResult Index()
        {
            return View(_db.Livros.ToList());
        }

        [Route("criar")]
        public ActionResult Create()
        {
            var categorias = _db.Categorias.ToList();
            var model = new EditorBookViewModel
            {
                Nome = "",
                ISBN = "",
                CategoriaId = 0,
                CategoriaOptions = new SelectList(categorias, "Id", "Nome")
            };

            return View(model);
        }

        [Route("criar")]
        [HttpPost]
        public ActionResult Create(EditorBookViewModel model)
        {
            if (!ModelState.IsValid) //faz o double check para ver se os dados são validos (já que no cliente o individuo consegue burlar)
            {
                var categorias = _db.Categorias.ToList(); //é o que está no Create Get
                model.CategoriaOptions = new SelectList(categorias, "Id", "Nome");
                return View(model);
            }

            var livro = new Livro();
            livro.Nome = model.Nome;
            livro.ISBN = model.ISBN;
            livro.DataLancamento = model.DataLancamento;
            livro.CategoriaId = model.CategoriaId;
            _db.Livros.Add(livro);
            try
            {
                throw new Exception("Falha no banco");
                _db.SaveChanges();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Mensagem", ex.Message);
                var categorias = _db.Categorias.ToList();
                model.CategoriaOptions = new SelectList(categorias, "Id", "Nome");
                return View(model);
            }

            return RedirectToAction("Index");
        }

        [Route("editar")]
        public ActionResult Edit(int id)
        {
            var categorias = _db.Categorias.ToList();
            var livro = _db.Livros.Find(id);

            var model = new EditorBookViewModel
            {
                Nome = livro.Nome,
                ISBN = livro.ISBN,
                CategoriaId = livro.CategoriaId,
                CategoriaOptions = new SelectList(categorias, "Id", "Nome")
            };

            return View(model);
        }

        [Route("editar")]
        [HttpPost]
        public ActionResult Edit(EditorBookViewModel model)
        {
            var livro = _db.Livros.Find(model.Id);
            _db.Entry<Livro>(livro).State = System.Data.Entity.EntityState.Modified;
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

BoookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css") <!-- Styles.Render renderiza css -->
    @Styles.Render("~/Content/custom") 
    @Scripts.Render("~/bundles/modernizr") <!-- Scripts.Render renderiza js -->
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Livros", "Index", "Livro")</li> <!-- action Link é um href-->
                    <li>@Html.ActionLink("About", "About", "Home")</li> <!-- dio error -->
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BoookStore/Views/Shared/_LayoutNovo.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_LayoutNovo</title>
    <link rel="stylesheet" href="https://bootswatch.com/materia/bootstrap.min.css" media="all"/>
</head>
<body>
    @if (IsSectionDefined("menu"))
    {
        <div class="col-md-4">
            <h3>Menu</h3>
            @RenderSection("menu", false) <!-- true obriga que todas as views renderizem o Menu-->
        </div>
    }

    <div class="container well col-md-8">
        @RenderBody()
    </div>

    @RenderSection("Scripts", false)
</body>
</html>